<center><h1>Raj Panchasara</h1></center>
<center><h1>23010101185</h1></center><br>
<center><h2>Model Creation</h2></center>

# Week 3 Task :

## Import library

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

## Import various algorithms

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

## 1. Load Clean Dataset

In [4]:
df = pd.read_csv("cardio_train_clean.csv")
df.head()

,id,age,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,gender_Male,height_m,bmi
0,0,50.0,168,62.0,110,80,1,1,0,0,1,0,False,1.68,21.967120
1,1,55.0,156,85.0,140,90,3,1,0,0,1,1,True,1.56,34.927679
2,2,52.0,165,64.0,130,70,3,1,0,0,0,1,True,1.65,23.507805
3,3,48.0,169,82.0,150,100,1,1,0,0,1,1,False,1.69,28.710479
4,8,60.0,151,67.0,120,80,2,2,0,0,0,0,True,1.51,29.384676

## Split Features and Target

In [5]:
X = df.drop("cardio", axis=1)
y = df["cardio"]

In [6]:
X

,id,age,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,gender_Male,height_m,bmi
0,0,50.0,168,62.0,110,80,1,1,0,0,1,False,1.68,21.967120
1,1,55.0,156,85.0,140,90,3,1,0,0,1,True,1.56,34.927679
2,2,52.0,165,64.0,130,70,3,1,0,0,0,True,1.65,23.507805
3,3,48.0,169,82.0,150,100,1,1,0,0,1,False,1.69,28.710479
4,8,60.0,151,67.0,120,80,2,2,0,0,0,True,1.51,29.384676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62500,99991,54.0,172,70.0,130,90,1,1,0,0,1,True,1.72,23.661439
62501,99992,58.0,165,80.0,150,80,1,1,0,0,1,True,1.65,29.384757
62502,99993,53.0,168,76.0,120,80,1,1,1,0,1,False,1.68,26.927438
62503,99998,61.0,163,72.0,135,80,1,2,0,0,0,True,1.63,27.099251
62504,99999,56.0,170,72.0,120,80,2,1,0,0,1,True,1.70,24.913495

In [7]:
y

0        0
1        1
2        1
3        1
4        0
        ..
62500    1
62501    1
62502    0
62503    1
62504    0
Name: cardio, Length: 62505, dtype: int64

## Train–Test Split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=18,
    stratify=y
)

In [9]:
results = []

## K-Nearest Neighbors (KNN)

In [10]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)
acc = accuracy_score(y_test, y_pred_knn)

In [11]:
name = 'K-Nearest Neighbors'

print("KNN Accuracy:", acc*100)

results.append({
        "Algorithm": name,
        "Accuracy": acc
    })

KNN Accuracy: 63.426925845932324

## Decision Tree

In [12]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)
acc = accuracy_score(y_test, y_pred_dt)

In [13]:
name = 'Decision Tree'

print("Decision Tree Accuracy:", acc*100)

results.append({
        "Algorithm": name,
        "Accuracy": acc
    })

Decision Tree Accuracy: 63.234941204703624

## Support Vector Machine (SVM)

In [14]:
from sklearn.svm import SVC

svm = SVC()
svm.fit(X_train, y_train)

y_pred_svm = svm.predict(X_test)
acc = accuracy_score(y_test, y_pred_svm)

In [15]:
name = 'Support Vector Machine'

print("SVM Accuracy:", acc*100)

results.append({
        "Algorithm": name,
        "Accuracy": acc
    })

SVM Accuracy: 50.61195104391649

## Naive Bayes

In [16]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(X_train, y_train)

y_pred_nb = nb.predict(X_test)
acc = accuracy_score(y_test, y_pred_nb)

In [17]:
name = 'Naive Bayes'

print("Naive Bayes Accuracy:", acc*100)

results.append({
        "Algorithm": name,
        "Accuracy": acc
    })

Naive Bayes Accuracy: 71.4742820574354

## Gradient Boosting

In [18]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(random_state=42)
gb.fit(X_train, y_train)

y_pred_gb = gb.predict(X_test)
acc = accuracy_score(y_test, y_pred_gb)

In [19]:
name = 'Gradient Boosting'

print("Gradient Boosting Accuracy:", acc*100)

results.append({
        "Algorithm": name,
        "Accuracy": acc
    })

Gradient Boosting Accuracy: 73.31413486921046

## Random Forest

In [24]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=18)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)
acc_rf = accuracy_score(y_test, y_pred_rf)

In [25]:
name = 'Random Forest'

print("Random Forest Accuracy:", acc*100)

results.append({
        "Algorithm": name,
        "Accuracy": acc
    })

Random Forest Accuracy: 73.31413486921046

## Accuracy Comparison Table

In [22]:
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by="Accuracy", ascending=False)
results_df

                Algorithm  Accuracy
4       Gradient Boosting  0.733141
5           Random Forest  0.733141
3             Naive Bayes  0.714743
0     K-Nearest Neighbors  0.634269
1           Decision Tree  0.632349
2  Support Vector Machine  0.506120

## Best Algorithm

In [23]:
best_model = results_df.iloc[0]
print("Best Fitting Algorithm :", best_model.Algorithm)

Best Fitting Algorithm : Gradient Boosting

## Last Output of week 3 task

# Best Algorithms are Random Forest & Gradient Boosting